# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=interligada2023
      - MARIADB_DATABASE=interligada
      - MARIADB_PASSWORD=#interligada

  interligada:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=interligada2023
      - DB_DATABASE=interligada
      - DB_PASSWORD=#interligada
    volumes:
      - './api:/app'
    depends_on:
      - mariadb